# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-24 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cistern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('max_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cistern_type', models.CharField(choices=[('box', 'куб'), ('hc', 'горизонтальный цилиндр'), ('vc', 'вертикальный цилиндр')], max_length=3)),
                ('name', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(default='0', max_length=20)),
                ('speed', models.PositiveIntegerField(default=115200)),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_id', models.CharField(max_length=20)),
                ('dosed', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date_time', models.DateTimeField()),
                ('add', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('cistern_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fuel_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('delete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KeyOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=40)),
                ('car', models.CharField(default='', max_length=40)),
                ('keys', models.CharField(max_length=16, unique=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cistern', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loads.Cistern')),
            ],
        ),
        migrations.CreateModel(
            name='Licenced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateField()),
                ('trial', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UpDosed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('volume', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comment', models.TextField(blank=True, null=True)),
                ('cistern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.Cistern')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='database',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.KeyOwner'),
        ),
        migrations.AddField(
            model_name='cistern',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loads.FuelType'),
        ),
    ]
